theme: jekyll-theme-slate
title: Naive Wang's Nowhere Land
spotify: <iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/20LrcgK75Q8W5C9NiH481P?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
google_analytics: G-LJWVW5NGYE
