theme: jekyll-theme-slate
title: Naive Wang's Nowhere Land
instagram: https://www.instagram.com/naive_wong
imdb: https://www.imdb.com/user/ur81712375
spotify: <iframe src="https://open.spotify.com/embed/album/2ulH3OJDTytz1ZsQ8LFlno?utm_source=generator" width="100%" height="80" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>